### ISSUE TITLE
couple of things

### ISSUE THREAD

**Issue by cagjony** [nerf-common/channelmap-generation#1]
First of all, thank you very much for making this collaborative and sharing the repo with us,

I have a couple of things might be useful for documentation and syntax related issues,

1) DOCUMENTATION/SYNTAX: Instead of downloading and installing from pip, how can I build from the source code? In this way, I can immediately change and request to merge with you.
python setup.py install
gives quite some errors related to numpy

2) DOCUMENTATION:  can you provide some information regarding packages required for fresh environment (e.g. anaconda) install (I have seen yaml file but I think it is not complete maybe you can modify your requirements.txt with the packages given below). 

the ones that are prompted to me during the fresh install.
- scipy
-regex
- matplotlib

3) DOCUMENTATION: Another thing is which python version is used for this repository (2,7 or 3.bla.ba), have you ever tested to run it on Windows? or it is only written for linux?

4) DOCUMENTATION/SYNTAX: since you are giving snippets of code to run, it is better to have jupyter notebook and example channel maps to play with the repository.

5) SYNTAX: the most important comment is related to the channelmap file. if you open .channelmap file with pandas and try to convert it to .prb file by using sorting repository (old repo), you will see that the columns are different such as, 
this is the correct order:
"Probe,Data,X,Y,Disconnect,Shank" 
this is what you have it in probes.py
 file.write("Probe,Data,Disconnect,X,Y,Shank\n")

I have just fly over the code, now I can start running it :D

**Comment by MarineChap** [comment]
You need to assign me when you add an issue (on the right). If you don't do it, I won't see it. 

1-2. I take note of the installation and package environment lack of documentation. 
commit = 8b44b18056c0b789ff4c4c6b9a937ab1d3c05200

3. Of course, it is in python 3. Python 2.xx is not supported anymore - no development should be done in this version.  
commit = 2b613bd6eb617f384a5484cddf1ed2f40008adf4
I did not test it on window (I don't have this os). You can try, I don't see why it should not working. Keep me posted

4. I already have a jupyter notebook integrated in the documentation. However, it is a previous version of the module. Some stuffs are differents. You can look  [here](https://kloostermannerflab.bitbucket.io/notebooks/Kilosort/Create%20a%20channel%20map.html) if you want
But there are only 3 lines of codes ... not sure the notebook is useful. I can add it later in the nerfcluster doc if really needed. 

5. Good catch. Don't hesitate to do the modification in a branch

**Comment by nerf-common** [comment]
Hi @cagjony , about the bullet 5 that you pointed out, do you have the modification Probe,Data,X,Y,Disconnect,Shank in a working copy?

**Comment by cagjony** [comment]
no, I have not updated and tested the toolbox yet. I can have a look at it when I have some time. By the way, we have to integrate channelmap to .prb file conversion with the help of sorting repository in bitbucket. How are we going to do it?

**Comment by MarineChap** [comment]
That's not very difficult. You can just add a conversion step in the spike sorting script based on the extension given by the user.
Edit: My bad, I forget the state of the project. The conversion in prb file existing in the nerf cluster is in Matlab or Python? I can look Monday how to integrate it to this repo.

**Comment by cagjony** [comment]
it is in python and I think as far as I know it is in sorting repository and the name of the function is probe.py

**Comment by MarineChap** [comment]
Okay I will integrate it. And also do the modif of the point 5.

**Comment by MarineChap** [comment]
@cagjony  what is poly2 probes? The code in the bitbucket repo is based a lot on this design? What is it and do we still need it?

Edit : in fact same question for all these designs : 
poly2s
poly2
linear
poly2+linear_16
poly3
neuroseeker

**Comment by cagjony** [comment]
poly2 is a type of probe that has 2 columns ,poly3 has 3 columns, linear has 1 column, neuroseeker is something similar to neuropixels but has many more columns. They were the ones I have used in my previous studies. Recently we only need to integrate poly2 and the rest is not necessary since we start using neuropixels.

**Comment by MarineChap** [comment]
I just saw that Joao is contributing on the other repository. Can he contributes here too? That's very difficult to take a code written by someone else long time ago. @gmaggi   Can you add him to the repo ? 
In parallel, I did my own development. Can you either test it or gives me both a tetrode configuration and the corresponding prb file please ?

**Comment by cagjony** [comment]
maybe you can ask Fred to make the test because unfortunately, I do not have any time to test the spikeinterface analysis stream. Sorry

**Comment by gmaggi** [comment]
Hi,
@MarineChap , https://github.com/nerf-common/from_external_packages/commit/36451fb24f137102f388117c77edd8c175698b67 was me, no Joao . 
I don't know how my commit from mouselab@nerfcluster-fs appears in the Joao's name, just tested and happened again.

The issues still is converting a .channelmap to .prb" using Joao's tool?

**Comment by MarineChap** [comment]
I don't think Fred has the time either. Don't worry I will find someone in the lab. 

@gmaggi  Did you commit in ssh or http ? If you commit in ssh, maybe there is a ssh config file somewhere in the nerf cluster with the joao identifiant. 
Maybe send him an email because you are using it own personal account right now... 

Not really an issue I just don't have the time to look so much legacy codes. ;) But I did develop the function myself. Promise I am trying to test it as soon as can.
