### ISSUE TITLE
csv channelmap instead of prb channelmap

### ISSUE THREAD

**Issue by MarineChap** [nerf-common/channelmap-generation#2]
Do we really need to have the prb format for the channelmap ? Spike Interface is also reading the csv format (which a looot much easier).

@gmaggi  @cagjony

**Comment by gmaggi** [comment]
I think the .prb should be kept, as I've seen people use to use that format.
If people need the csv format, that also could be implemented. Is csv occupied?

-Giuliano.

**Comment by MarineChap** [comment]
For me, it was just used because of the module developed in the bitbucket nerf repo no? From what I saw (in my lab), people does not really use prb file because there are not using the main functionality which is grouping the channels. So, it means we are using a format where errors can be easily done without using the + of this format. 
At least, it would be nice to have both formats. I will open an issue in the concerned repo.

**Comment by gmaggi** [comment]
I'll take care of the conversion .channelmap -> .prb
@MarineChap , could you create the patch for .csv? 

-Giuliano.

**Comment by MarineChap** [comment]
Sorry this day, I am deeply into falcon in C++. I can eventually do it one day when I switch to python again. 

What do you mean by you'll take care of the conversion .channelmap -> prb file? 

I already implemented the prb generation file in this repository. The only missing thing is a real test.

**Comment by gmaggi** [comment]
Hi @MarineChap , I might have lost a bit the thread with the discussion. I thought we wanted to integrate Joao's method to covert .channelmap to .prb into your channelmap-generation. If this actually is not intended, and that functionality already exists in channelmap-generation, could you provide a minimal example how to use it?.  

-Giuliano

**Comment by MarineChap** [comment]
The minimal code is in the readme. Instead that, at the end when specifying the format file, you just give "prb" instead of "channelmap"

**Comment by gmaggi** [comment]
It would be like: hdw.create_channel_map(path=/path/to/place/the/generated/file.prb, map_format="prb") ?

**Comment by MarineChap** [comment]
The path is the path for the folder. I can eventually add later an option parameter to set another filename than the automatical name chosen by the implementation if you prefer. 

`hdw =  probes("tetrodes", nb_tetrode)` for an example with tetrodes
`hdw.create_channel_map(path="/path/to/place/the/generated", map_format="prb")`

**Comment by gmaggi** [comment]
I think I am still missing something, What Joao's tools does: pass an existing `.channelmap` file, and the same `.channnelmap` file is converted to `.prb` format. In yours, where could I pass an existing file.channelmap and convert it to .prb?

**Comment by MarineChap** [comment]
It does not make sense anymore to transform channelmap file in prb file. You just have to give the type of your probe and you will have directly the right channelmap with the right format with your data. 

However, if you really think, it is a need, I can easily implement an option to transform from a format to another. I still think it will introduce errors coming from people using a channelmap found on internet without verifying if it is indeed corresponding to their data...

**Comment by gmaggi** [comment]
I think users would appreciate to have the functionally. If you can implement it, it would be great.

-Giuliano.

**Comment by MarineChap** [comment]
The commit just before your comment is implementing the feature you asked. You can look in the readme to see how to use it.

**Comment by MarineChap** [comment]
@gmaggi  did you test it ? What is your feedback ?

**Comment by gmaggi** [comment]
Hi @MarineChap , I've not tried, I could do it by tomorrow. I let you know.

**Comment by gmaggi** [comment]
Hi @MarineChap , I installed it as `pip install git+https://github.com/nerf-common/channelmap-generation.git`, but I get output below. Do I miss anything?

`(channelmap) giuliano@nerfcluster-fs:~/template_file$ python -c "from py_channelmap import probes"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/export/home/giuliano/anaconda/installation/lib/python3.7/site-packages/py_channelmap/__init__.py", line 1, in <module>
    from .probes import probes
  File "/export/home/giuliano/anaconda/installation/lib/python3.7/site-packages/py_channelmap/probes.py", line 14, in <module>
    from .neuropixels.spikeGLX import neuropixels
ModuleNotFoundError: No module named 'py_channelmap.neuropixels'
`

**Comment by MarineChap** [comment]
@gmaggi 
That's very surprising ... I did not success to reproduce it but as I have a little guess on what could cause the error... I changed the import path. Tell me if it fixed your problem.

**Comment by gmaggi** [comment]
Hi @MarineChap , I upgraded as : `pip install -U git+https://github.com/nerf-common/channelmap-generation.git` , but I still have an error, see below. I also post the output of the `ls` command in `py_channelmap`, is this missing something?

`(channelmap) giuliano@nerfcluster-fs:~$ python -c "from py_channelmap import probes"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/export/home/giuliano/anaconda/installation/lib/python3.7/site-packages/py_channelmap/__init__.py", line 1, in <module>
    from .probes import probes
  File "/export/home/giuliano/anaconda/installation/lib/python3.7/site-packages/py_channelmap/probes.py", line 14, in <module>
    from py_channelmap.neuropixels.spikeGLX import neuropixels
ModuleNotFoundError: No module named 'py_channelmap.neuropixels'
(channelmap) giuliano@nerfcluster-fs:~$ ls /export/home/giuliano/anaconda/installation/lib/python3.7/site-packages/py_channelmap
__init__.py  __init__.py~  probes.py  __pycache__  template_probes.py  tetrodes.py  _version.py
(channelmap) giuliano@nerfcluster-fs:~$`

**Comment by MarineChap** [comment]
I forget to modify the init file ! sorry, you can try again.

**Comment by gmaggi** [comment]
Hi @MarineChap , I still get the issue. I actually re-installed my entire channelmap env, and the same error pops up:

`(channelmap) giuliano@nerfcluster-fs:~/anaconda$ python -c "from py_channelmap import probes"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/export/home/giuliano/anaconda/installation/envs/channelmap/lib/python3.6/site-packages/py_channelmap/__init__.py", line 1, in <module>
    from py_channelmap.probes import probes
  File "/export/home/giuliano/anaconda/installation/envs/channelmap/lib/python3.6/site-packages/py_channelmap/probes.py", line 14, in <module>
    from py_channelmap.neuropixels.spikeGLX import neuropixels
ModuleNotFoundError: No module named 'py_channelmap.neuropixels'
` 

Could it be that the neuropixels subfolder is missing?. Below is what I see from the `ls`, also is shown in the attachment.

`(channelmap) giuliano@nerfcluster-fs:~/anaconda$ ls /export/home/giuliano/anaconda/installation/envs/channelmap/lib/python3.6/site-packages/py_channelmap
__init__.py  probes.py  __pycache__  template_probes.py  tetrodes.py  _version.py
(channelmap) giuliano@nerfcluster-fs:~/anaconda$ 
`
<img width="1382" alt="Screen Shot 2020-05-18 at 1 00 18 PM" src="https://user-images.githubusercontent.com/11243913/82205906-98775680-9907-11ea-8c61-93490822a80a.png">

**Comment by MarineChap** [comment]
Oh I did not noticed that you were using pip install! And you discovered a thing I did not catch in my setup file. I did not put neuropixels as an independent module because for me we did not need to do that but... Apparently if I don't put it as a module, it will not be download at all. 
That's make sense but I never noticed these behavior. Sorry It tooks me so many times.

**Comment by gmaggi** [comment]
Hi @MarineChap , After upgrading, I got a new error, which points to the line: `packages=["py_channelmap", "py_channelmap.neuropixels],`

**Comment by MarineChap** [comment]
Why you don't clone the repo ? This error was very easy to correct --> I forget the end guillemet. We would both win time. ;) I will correct it.
