### ISSUE TITLE
Wrong metafile used for channelmap generation

### ISSUE THREAD

**Issue by MarineChap** [nerf-common/channelmap-generation#3]
@gmaggi 
I will fix the wrong selection of the metafile when having multiprobes in the same folder. Can you update it in the nerfcluster once it is done please ? 
You can directly pass the bin input name now.

**Comment by MarineChap** [comment]
In fact as for spikeglx it is not needed by spike interface maybe we should discuss of fully removing this channel generation step from the spike sorting pipeline. 

Problem now in the pipeline:

It creates some file noises by taking the wrong metafile and generating the wrong channelmap while in background spike interface is taking the right file. 

Conclusion: Not used anymore and generating wrong file in the output folder.

**Comment by MarineChap** [comment]
Also another lead would be to make use of a similar package being developed right now by spike interface team much more robust ! 
https://github.com/SpikeInterface/probeinterface

**Comment by gmaggi** [comment]
Hi @MarineChap 

Indeed, for `glx` it is not needed. However, some users might need to convert `.channelmap` to `.prb`. It would be convenient then to keep this channel-map generation in the nerfcluster for that purpose.

**Comment by MarineChap** [comment]
Hi @gmaggi  Okay but at least, can you update following the correction I did by sending the data input for spikeglx data instead of the meta file.
Right now, Hanna for example, has her data correctly spike sorted with the imec1.ap.meta file but the channelmap generated is the one corresponding with imec0.ap.meta. That's very confusing.

**Comment by gmaggi** [comment]
Hi @MarineChap , I upgraded the py-channelmap in the nerfcluster according to your last patch. To test, this is in a cloned environment, for this purpose you could use the installation in /export/home/mouselab/users/Hanna/git-nerf-common/from_external_packages/
Remember to use the option `--use_test`.
Let me know if that works, so I can update the central installation.

**Comment by MarineChap** [comment]
Perfect ! I just tested this morning ! All working :) 

Very practical this --use_test
